spring.application.name=bookstore

# Server
server.port=8080

# API Configuration
api.prefix=/api/v1

# PostgreSQL DB Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/book-store
spring.datasource.username=postgres
spring.datasource.password=123456