spring.application.name=bookstore

# Server
server.port=8080

# API Configuration
api.prefix=/api/v1

# PostgreSQL DB Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/book-store
spring.datasource.username=postgres
spring.datasource.password=123456

# Cloudinary Config
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${API_KEY}
cloudinary.api-secret=${API_SECRET}

jwt.signerKey=${JWT_SIGNER_KEY}

#Email Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Activation URL config
app.activation-url=http://localhost:8080/api/v1/auth

# Mỗi file ảnh tối đa 10MB
spring.servlet.multipart.max-file-size=10MB
# Tổng một lượt upload (ví dụ tối đa 5 ảnh) là 50MB
spring.servlet.multipart.max-request-size=50MB